/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6pHvq9hEK1w
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"

export function Component() {
  return (
    <>
      <header className="bg-gray-900 text-white py-4 shadow-md">
        <div className="container mx-auto flex items-center justify-between">
          <a className="flex items-center gap-2" href="#">
            <LaptopIcon className="h-8 w-8" />
            <span className="text-xl font-bold">Linux Learning Hub</span>
          </a>
          <nav className="hidden md:flex items-center gap-6">
            <Link className="hover:text-gray-300" href="#">
              Tutorials
            </Link>
            <Link className="hover:text-gray-300" href="#">
              Resources
            </Link>
            <Link className="hover:text-gray-300" href="#">
              Community
            </Link>
            <Link className="hover:text-gray-300" href="#">
              About
            </Link>
            <div className="flex items-center gap-2">
              <Link className="hover:text-gray-300" href="#">
                Login
              </Link>
              <Link className="bg-blue-500 hover:bg-blue-600 px-4 py-2 rounded-md" href="#">
                Register
              </Link>
            </div>
          </nav>
          <button className="md:hidden">
            <MenuIcon className="h-6 w-6" />
          </button>
        </div>
      </header>
      <main>
        <section className="bg-gray-900 text-white py-20">
          <div className="container mx-auto flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="space-y-4 max-w-md">
              <h1 className="text-4xl font-bold">Welcome to Linux Learning Hub</h1>
              <p className="text-gray-300">
                Explore the world of Linux and become a proficient user. Our comprehensive tutorials and resources will
                guide you through the journey.
              </p>
              <Link className="bg-blue-500 hover:bg-blue-600 px-6 py-3 rounded-md font-medium" href="#">
                Get Started
              </Link>
            </div>
            <img
              alt="Linux Hero"
              className="max-w-full"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/400",
                objectFit: "cover",
              }}
              width={500}
            />
          </div>
        </section>
        <section className="py-16">
          <div className="container mx-auto">
            <div className="space-y-8">
              <div className="text-center">
                <h2 className="text-3xl font-bold">Our Mission</h2>
                <p className="text-gray-600 max-w-3xl mx-auto">
                  At Linux Learning Hub, our mission is to empower individuals of all skill levels to master the Linux
                  operating system. We believe that open-source technology should be accessible and user-friendly for
                  everyone.
                </p>
              </div>
              <div>
                <h2 className="text-3xl font-bold mb-4">Popular Tutorials</h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6">
                  <Card>
                    <CardHeader>
                      <CardTitle>1-Day Linux Crash Course</CardTitle>
                      <CardDescription>Get up and running with Linux in just one day.</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm">
                        Dive into the essentials of Linux, including file management, command-line basics, and user
                        administration.
                      </p>
                    </CardContent>
                    <CardFooter>
                      <div className="flex flex-col items-center">
                        <Link className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md mb-2" href="#">
                          Start Learning
                        </Link>
                      </div>
                    </CardFooter>
                  </Card>
                  <Card>
                    <CardHeader>
                      <CardTitle>2-Day Linux Fundamentals</CardTitle>
                      <CardDescription>Solidify your understanding of Linux in two days.</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm">
                        Explore the Linux file system, shell scripting, and system administration basics.
                      </p>
                    </CardContent>
                    <CardFooter>
                      <div className="flex flex-col items-center">
                        <Link className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md mb-2" href="#">
                          Start Learning
                        </Link>
                      </div>
                    </CardFooter>
                  </Card>
                  <Card>
                    <CardHeader>
                      <CardTitle>3-Day Linux Mastery</CardTitle>
                      <CardDescription>Become a Linux power user in just three days.</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm">
                        Dive deeper into Linux, including advanced shell scripting, system optimization, and security
                        management.
                      </p>
                    </CardContent>
                    <CardFooter>
                      <div className="flex flex-col items-center">
                        <Link className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md mb-2" href="#">
                          Start Learning
                        </Link>
                      </div>
                    </CardFooter>
                  </Card>
                  <Card>
                    <CardHeader>
                      <CardTitle>4-Day Linux Administration</CardTitle>
                      <CardDescription>Learn to manage and maintain Linux systems.</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm">
                        Explore advanced system administration tasks, including user management, package installation,
                        and service configuration.
                      </p>
                    </CardContent>
                    <CardFooter>
                      <div className="flex flex-col items-center">
                        <Link className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md mb-2" href="#">
                          Start Learning
                        </Link>
                      </div>
                    </CardFooter>
                  </Card>
                  <Card>
                    <CardHeader>
                      <CardTitle>5-Day Linux DevOps</CardTitle>
                      <CardDescription>Integrate Linux into your DevOps workflow.</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm">
                        Learn to use Linux for infrastructure automation, containerization, and continuous
                        integration/deployment.
                      </p>
                    </CardContent>
                    <CardFooter>
                      <div className="flex flex-col items-center">
                        <Link className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md mb-2" href="#">
                          Start Learning
                        </Link>
                      </div>
                    </CardFooter>
                  </Card>
                </div>
              </div>
              <div>
                <h2 className="text-3xl font-bold mb-4">Featured Resources</h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                  <Card>
                    <CardHeader>
                      <CardTitle>Linux Essentials e-Book</CardTitle>
                      <CardDescription>A comprehensive guide to the Linux operating system.</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm">
                        Dive deep into the fundamentals of Linux, including installation, file management, and user
                        administration.
                      </p>
                    </CardContent>
                    <CardFooter>
                      <Link className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md" href="#">
                        Download
                      </Link>
                    </CardFooter>
                  </Card>
                  <Card>
                    <CardHeader>
                      <CardTitle>Linux Administration Masterclass</CardTitle>
                      <CardDescription>Video course on advanced Linux system administration.</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm">
                        Learn to manage complex Linux environments, including server configuration, security, and
                        automation.
                      </p>
                    </CardContent>
                    <CardFooter>
                      <Link className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md" href="#">
                        Enroll Now
                      </Link>
                    </CardFooter>
                  </Card>
                  <Card>
                    <CardHeader>
                      <CardTitle>Linux Command Line Cheatsheet</CardTitle>
                      <CardDescription>Quick reference guide for essential Linux commands.</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm">
                        Keep this handy cheatsheet nearby to quickly look up commonly used Linux commands and their
                        syntax.
                      </p>
                    </CardContent>
                    <CardFooter>
                      <Link className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md" href="#">
                        Download
                      </Link>
                    </CardFooter>
                  </Card>
                </div>
              </div>
              <div className="text-center">
                <h2 className="text-3xl font-bold">Join Our Community</h2>
                <p className="text-gray-600 max-w-3xl mx-auto">
                  Connect with fellow Linux enthusiasts, ask questions, share your projects, and contribute to the
                  growth of the Linux ecosystem.
                </p>
                <Link
                  className="bg-blue-500 hover:bg-blue-600 text-white px-6 py-3 rounded-md font-medium mt-4"
                  href="#"
                >
                  Explore Community
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-white py-8">
        <div className="container mx-auto flex flex-col md:flex-row items-center justify-between">
          <div className="flex items-center gap-2">
            <LaptopIcon className="h-8 w-8" />
            <span className="text-xl font-bold">Linux Learning Hub</span>
          </div>
          <nav className="flex items-center gap-6 mt-4 md:mt-0">
            <Link className="hover:text-gray-300" href="#">
              Tutorials
            </Link>
            <Link className="hover:text-gray-300" href="#">
              Resources
            </Link>
            <Link className="hover:text-gray-300" href="#">
              Community
            </Link>
            <Link className="hover:text-gray-300" href="#">
              About
            </Link>
          </nav>
        </div>
      </footer>
    </>
  )
}

function LaptopIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
